ConversationBundle\Entity\UsersConversations:
    type: entity
    table: users_conversations
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        conversationid:
            type: integer
            nullable: false
            options:
                unsigned: false
        userid:
            type: integer
            nullable: false
            options:
                unsigned: false
        labelconversation:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: labelConversation
    lifecycleCallbacks: {  }
