home_view:
    path:     /home
    defaults: { _controller: ConversationBundle:Conversation:view }
addMessage:
    path:     /message
    defaults: { _controller: ConversationBundle:Conversation:addMessage }
