<?php

namespace AuthBundle\Repository;

/**
 * AuthentificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthentificationRepository extends \Doctrine\ORM\EntityRepository
{
}
