<?php

namespace ConversationBundle\Repository;

/**
 * UsersConversationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersConversationsRepository extends \Doctrine\ORM\EntityRepository
{
}
